const canvas=document.querySelector("#chapter3-canvas"),ctx=canvas.getContext("2d"),caption=document.querySelector("#cinema-caption"),skip=document.querySelector("#skip-capture"),card=document.querySelector("#chapter3-card");
let width=1280,height=720,start=performance.now(),finished=false;
const agents=[[-.1,.52,-.12,0],[1.1,.5,.12,0],[.16,1.15,-.06,.04],[.84,1.15,.06,.04],[.5,-.22,0,-.06]];
resize();requestAnimationFrame(loop);window.addEventListener("resize",resize);skip.addEventListener("click",()=>{start=performance.now()-7200;finish()});
function resize(){const rect=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);width=Math.max(320,rect.width);height=Math.max(360,rect.height);canvas.width=Math.round(width*d);canvas.height=Math.round(height*d);ctx.setTransform(d,0,0,d,0,0)}
function loop(now){const elapsed=(now-start)/1000, d=Math.min(2,devicePixelRatio||1);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,width,height);if(elapsed<5.15)drawAlley(elapsed);else drawCell(elapsed);updateCaption(elapsed);if(elapsed>=6.7)finish();if(!finished)requestAnimationFrame(loop)}
function updateCaption(t){caption.textContent=t<1.5?"철교 너머, 인기척 없는 골목…":t<3.8?"검은 정장의 요원 다섯 명이 WH를 포위했다.":t<5.2?"시야가 검게 닫힌다.":"차가운 금속음. WH는 낯선 입체도형 안에서 눈을 떴다."}
function drawAlley(t){const g=ctx.createLinearGradient(0,0,0,height);g.addColorStop(0,"#242638");g.addColorStop(.65,"#11141f");g.addColorStop(1,"#070910");ctx.fillStyle=g;ctx.fillRect(0,0,width,height);ctx.fillStyle="#0b0d14";ctx.fillRect(0,height*.68,width,height*.32);ctx.strokeStyle="#323746";ctx.lineWidth=16;for(let x=-100;x<width+150;x+=220){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+180,height*.68);ctx.stroke()}const whX=width*(.35+Math.min(t/1.5,1)*.1),whY=height*.7;drawWH(whX,whY,t<1.5?Math.sin(t*12)*5:0);const converge=Math.max(0,Math.min(1,(t-1.25)/2.2));for(const [sx,sy,tx,ty] of agents){const x=lerp(width*sx,whX+width*tx,converge),y=lerp(height*sy,whY+height*ty,converge);drawAgent(x,y,.85)}if(t>3.7){ctx.fillStyle=`rgba(0,0,0,${Math.min(1,(t-3.7)/1.25)})`;ctx.fillRect(0,0,width,height)}}
function drawCell(t){ctx.fillStyle="#060b11";ctx.fillRect(0,0,width,height);const cx=width/2,cy=height*.49,pulse=.45+Math.sin(t*2)*.08;ctx.strokeStyle=`rgba(78,150,161,${pulse})`;ctx.lineWidth=3;for(let inset=30;inset<Math.min(width,height)*.44;inset+=70){ctx.strokeRect(inset,inset*.55,width-inset*2,height-inset*1.1)}ctx.fillStyle="#101923";ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(cx,cy);ctx.lineTo(0,height);ctx.fill();ctx.beginPath();ctx.moveTo(width,0);ctx.lineTo(cx,cy);ctx.lineTo(width,height);ctx.fill();ctx.fillStyle="#16232d";ctx.fillRect(width*.42,height*.3,width*.16,height*.28);drawWH(cx,height*.73,0);ctx.fillStyle="#5cd1c5";ctx.font="900 14px system-ui";ctx.textAlign="center";ctx.fillText("CONTAINMENT A-01",cx,height*.2)}
function drawWH(x,y,bob){ctx.save();ctx.translate(x,y+bob);ctx.fillStyle="#1b8f88";roundRect(-23,-92,49,64,16);ctx.fill();ctx.fillStyle="#efc3a9";ctx.beginPath();ctx.arc(1,-118,28,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17223b";ctx.beginPath();ctx.arc(1,-128,29,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 10px system-ui";ctx.textAlign="center";ctx.fillText("WH",1,-56);ctx.restore()}
function drawAgent(x,y,scale){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle="#050609";roundRect(-30,-118,60,88,13);ctx.fill();ctx.fillStyle="#d2b29f";ctx.beginPath();ctx.arc(0,-145,27,0,Math.PI*2);ctx.fill();ctx.fillStyle="#050609";ctx.fillRect(-28,-166,56,20);ctx.fillStyle="#d9dde2";ctx.beginPath();ctx.moveTo(-7,-115);ctx.lineTo(7,-115);ctx.lineTo(0,-83);ctx.fill();ctx.fillStyle="#161c28";ctx.beginPath();ctx.moveTo(-5,-113);ctx.lineTo(5,-113);ctx.lineTo(0,-86);ctx.fill();ctx.strokeStyle="#050609";ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(-12,-32);ctx.lineTo(-15,0);ctx.moveTo(12,-32);ctx.lineTo(15,0);ctx.stroke();ctx.restore()}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function lerp(a,b,t){return a+(b-a)*t}function finish(){if(finished)return;finished=true;card.classList.remove("is-hidden");caption.classList.add("is-hidden");skip.classList.add("is-hidden")}
