import { SPRINKLER_POINTS, TANK_POINTS, evaluateSprinklerGraph, evaluateTankGraph } from "./graph-logic.mjs";
import { assetManager } from "./asset-manager.mjs";

const canvas=document.querySelector("#map24-canvas"),ctx=canvas.getContext("2d");
const ui={hud:document.querySelector("#map24-hud"),objective:document.querySelector("#map24-objective"),count:document.querySelector("#graph-count"),prompt:document.querySelector("#map24-prompt"),promptText:document.querySelector("#map24-prompt-text"),toast:document.querySelector("#map24-toast"),start:document.querySelector("#map24-start"),startButton:document.querySelector("#map24-start-button"),dialogue:document.querySelector("#map24-dialogue"),avatar:document.querySelector("#map24-avatar"),speaker:document.querySelector("#map24-speaker"),dialogueText:document.querySelector("#map24-dialogue-text"),dialogueNext:document.querySelector("#map24-dialogue-next"),panel:document.querySelector("#graph-panel"),close:document.querySelector("#graph-close"),tankStage:document.querySelector("#tank-stage"),sprinklerStage:document.querySelector("#sprinkler-stage"),success:document.querySelector("#schedule-success"),tankStep:document.querySelector("#tank-step"),sprinklerStep:document.querySelector("#sprinkler-step"),tankGraph:document.querySelector("#tank-graph"),sprinklerGraph:document.querySelector("#sprinkler-graph"),tankForm:document.querySelector("#tank-form"),tankFeedback:document.querySelector("#tank-feedback"),tankHint:document.querySelector("#tank-hint"),sprinklerForm:document.querySelector("#sprinkler-form"),sprinklerFeedback:document.querySelector("#sprinkler-feedback"),sprinklerHint:document.querySelector("#sprinkler-hint"),activate:document.querySelector("#activate-safe-window"),complete:document.querySelector("#map24-complete"),replay:document.querySelector("#map24-replay"),next:document.querySelector("#map24-next"),touch:document.querySelector("#map24-touch"),left:document.querySelector("#map24-left"),right:document.querySelector("#map24-right"),interact:document.querySelector("#map24-interact")};

const makeState=()=>({started:false,playerX:180,direction:1,cameraX:0,operatorSpoken:false,tankSolved:false,sprinklerSolved:false,waterOff:false,sprayLevel:1,nearby:null,tankHintIndex:0,sprinklerHintIndex:0,dialogueQueue:[],dialogueCallback:null,complete:false,walkTime:0,lastTime:performance.now()});
let state=makeState(),viewWidth=1280,viewHeight=720,groundY=540,toastTimer=null;
const keys={left:false,right:false};
const world={width:2860,operatorX:570,monitorX:1240,sprinklerX:2100,interactions:[{id:"operator",x:570,radius:90,label:"묘목 관리사와 대화"},{id:"monitor",x:1240,radius:105,label:"관수 제어 모니터 확인"}]};
const SAPLING_ASSET_KEYS=["props.saplings.sapling01","props.saplings.sapling02","props.saplings.sapling03","props.saplings.sapling04","props.saplings.sapling05","props.saplings.sapling06","props.saplings.sapling07"];
const NURSERY_BEDS=[90,360,780,1050,1450,1700,2440,2710];
const NURSERY_SAPLINGS=NURSERY_BEDS.flatMap((bedX,bedIndex)=>[-42,-14,14,42].map((offset,index)=>({
  x:bedX+offset,
  key:SAPLING_ASSET_KEYS[(bedIndex*5+index*3)%SAPLING_ASSET_KEYS.length],
  height:58+((bedIndex+index*2)%4)*8,
  flipX:(bedIndex+index)%2===0
})));

renderLineGraph(ui.tankGraph,TANK_POINTS,{minX:0,maxX:50,minY:80,maxY:200,xTicks:[0,10,20,30,40,50],yTicks:[100,120,140,160,180]});
renderLineGraph(ui.sprinklerGraph,SPRINKLER_POINTS,{minX:0,maxX:60,minY:0,maxY:14,xTicks:[0,10,20,30,40,50,60],yTicks:[0,6,12],safeBand:[35,40],now:32});
resize();assetManager.loadAll().catch((error)=>console.warn(error));requestAnimationFrame(loop);

ui.startButton.addEventListener("click",startGame);ui.dialogueNext.addEventListener("click",advanceDialogue);ui.close.addEventListener("click",()=>closePanel(ui.panel));ui.tankForm.addEventListener("submit",submitTank);ui.tankHint.addEventListener("click",showTankHint);ui.sprinklerForm.addEventListener("submit",submitSprinkler);ui.sprinklerHint.addEventListener("click",showSprinklerHint);ui.activate.addEventListener("click",activateSafeWindow);ui.replay.addEventListener("click",resetGame);ui.next.addEventListener("click",()=>{window.location.href="./2map5.html"});window.addEventListener("resize",resize);window.addEventListener("keydown",keyDown);window.addEventListener("keyup",keyUp);window.addEventListener("blur",clearMovement);bindHold(ui.left,"left");bindHold(ui.right,"right");ui.interact.addEventListener("pointerdown",event=>{event.preventDefault();interact()});

function renderLineGraph(svg,points,config){const left=58,right=592,top=25,bottom=250,width=right-left,height=bottom-top;const px=value=>left+(value-config.minX)/(config.maxX-config.minX)*width;const py=value=>bottom-(value-config.minY)/(config.maxY-config.minY)*height;let markup="";if(config.safeBand){const x=px(config.safeBand[0]),w=px(config.safeBand[1])-x;markup+=`<rect class="safe-band" x="${x}" y="${top}" width="${w}" height="${height}"/><text x="${x+w/2}" y="${top+16}" text-anchor="middle">안전</text>`}for(const value of config.yTicks){const y=py(value);markup+=`<line class="grid" x1="${left}" y1="${y}" x2="${right}" y2="${y}"/><text x="${left-10}" y="${y+5}" text-anchor="end">${value}</text>`}for(const value of config.xTicks){const x=px(value);markup+=`<line class="grid" x1="${x}" y1="${top}" x2="${x}" y2="${bottom}"/><text x="${x}" y="${bottom+24}" text-anchor="middle">${value}</text>`}markup+=`<line class="axis" x1="${left}" y1="${top}" x2="${left}" y2="${bottom}"/><line class="axis" x1="${left}" y1="${bottom}" x2="${right}" y2="${bottom}"/>`;if(config.now!==undefined){const x=px(config.now);markup+=`<line class="now-line" x1="${x}" y1="${top}" x2="${x}" y2="${bottom}"/><text x="${x+5}" y="${bottom-8}">현재 32분</text>`}markup+=`<polyline class="series" points="${points.map(point=>`${px(point.time)},${py(point.value)}`).join(" ")}"/>`;markup+=points.map(point=>`<circle class="point" cx="${px(point.time)}" cy="${py(point.value)}" r="6"/>`).join("");svg.innerHTML=markup}

function startGame(){state.started=true;state.lastTime=performance.now();ui.start.classList.add("is-hidden");ui.hud.classList.remove("is-hidden");if(matchMedia("(hover: none),(pointer: coarse)").matches)ui.touch.classList.remove("is-hidden");updateObjective();canvas.focus()}
function resetGame(){state=makeState();ui.tankForm.reset();ui.sprinklerForm.reset();ui.tankFeedback.textContent="";ui.sprinklerFeedback.textContent="";ui.tankStage.classList.remove("is-hidden");ui.sprinklerStage.classList.add("is-hidden");ui.success.classList.add("is-hidden");ui.tankStep.className="is-active";ui.sprinklerStep.className="";ui.complete.classList.add("is-hidden");ui.start.classList.remove("is-hidden");ui.hud.classList.add("is-hidden");ui.touch.classList.add("is-hidden");updateCount()}
function keyDown(event){if(event.target.matches?.("input,select,button"))return;if(["ArrowLeft","ArrowRight","a","A","d","D","e","E","Enter"," "].includes(event.key))event.preventDefault();if(event.key==="Escape"){if(!ui.panel.classList.contains("is-hidden"))closePanel(ui.panel);else if(!ui.dialogue.classList.contains("is-hidden"))advanceDialogue();return}if(event.key==="ArrowLeft"||event.key.toLowerCase()==="a")keys.left=true;if(event.key==="ArrowRight"||event.key.toLowerCase()==="d")keys.right=true;if((event.key==="Enter"||event.key===" ")&&!ui.dialogue.classList.contains("is-hidden"))return advanceDialogue();if(event.key.toLowerCase()==="e"||event.key==="Enter")interact()}
function keyUp(event){if(event.key==="ArrowLeft"||event.key.toLowerCase()==="a")keys.left=false;if(event.key==="ArrowRight"||event.key.toLowerCase()==="d")keys.right=false}
function bindHold(button,direction){const start=event=>{event.preventDefault();keys[direction]=true},stop=event=>{event.preventDefault();keys[direction]=false};button.addEventListener("pointerdown",start);button.addEventListener("pointerup",stop);button.addEventListener("pointercancel",stop);button.addEventListener("pointerleave",stop)}
function clearMovement(){keys.left=false;keys.right=false}

function loop(now){const dt=Math.min(.034,(now-state.lastTime)/1000||0);state.lastTime=now;update(dt);draw();requestAnimationFrame(loop)}
function update(dt){if(!state.started||state.complete)return;if(state.waterOff)state.sprayLevel=Math.max(0,state.sprayLevel-dt*.75);if(!paused()){let direction=0;if(keys.left)direction--;if(keys.right)direction++;if(direction){state.playerX+=direction*235*dt;state.direction=direction;state.walkTime+=dt*10;const limit=state.waterOff?world.width-70:1900;state.playerX=Math.max(70,Math.min(limit,state.playerX))}}updateNearby();updateCamera(dt);if(state.waterOff&&state.sprayLevel===0&&state.playerX>2670)completeMap()}
function paused(){return!ui.dialogue.classList.contains("is-hidden")||!ui.panel.classList.contains("is-hidden")}
function updateNearby(){if(paused()){state.nearby=null;ui.prompt.classList.add("is-hidden");return}let nearest=null,distance=Infinity;for(const item of world.interactions){const current=Math.abs(state.playerX-item.x);if(current<=item.radius&&current<distance){nearest=item;distance=current}}state.nearby=nearest?.id??null;if(nearest){ui.promptText.textContent=nearest.label;ui.prompt.classList.remove("is-hidden")}else ui.prompt.classList.add("is-hidden")}

function interact(){if(!state.started||paused()||!state.nearby)return;if(state.nearby==="operator"){if(!state.operatorSpoken){showDialogue([{speaker:"묘목 관리사",avatar:"관리",text:"자동 관수기가 통로 쪽까지 물을 뿜고 있어요. 하지만 어린 묘목 때문에 전원을 함부로 끌 수는 없습니다."},{speaker:"WH",avatar:"WH",text:"관수 기록에서 물이 나오지 않는 시간을 찾으면 일정은 지키면서 지나갈 수 있겠네요."},{speaker:"묘목 관리사",avatar:"관리",text:"맞아요. 먼저 물탱크의 변화가 정상인지 확인하고, 관수량 그래프의 반복 주기로 다음 안전 시간을 찾아 주세요."}],()=>{state.operatorSpoken=true;updateObjective()})}else showDialogue([{speaker:"묘목 관리사",avatar:"관리",text:state.waterOff?"그래프대로 무분사 구간이 시작됐어요. 지금 통로를 건너세요!":state.sprinklerSolved?"안전 시간 예약을 실행해 주세요.":"제어 모니터에서 두 그래프를 차례로 확인해 주세요."}]);return}if(state.nearby==="monitor"){if(!state.operatorSpoken){showToast("먼저 묘목 관리사에게 관수 상황을 들어 보자.");return}openMonitor()}}
function openMonitor(){if(state.sprinklerSolved){ui.tankStage.classList.add("is-hidden");ui.sprinklerStage.classList.add("is-hidden");ui.success.classList.remove("is-hidden")}else if(state.tankSolved){showSprinklerStage()}else showTankStage();openPanel(ui.panel)}
function showTankStage(){ui.tankStage.classList.remove("is-hidden");ui.sprinklerStage.classList.add("is-hidden");ui.success.classList.add("is-hidden");ui.tankStep.className="is-active";ui.sprinklerStep.className=""}
function showSprinklerStage(){ui.tankStage.classList.add("is-hidden");ui.sprinklerStage.classList.remove("is-hidden");ui.success.classList.add("is-hidden");ui.tankStep.className="is-complete";ui.sprinklerStep.className="is-active"}
function submitTank(event){event.preventDefault();const form=new FormData(ui.tankForm),result=evaluateTankGraph(form.get("description"),form.get("fastestDrop"));ui.tankFeedback.textContent=result.message;ui.tankFeedback.className=`form-feedback ${result.ok?"is-success":"is-error"}`;if(!result.ok)return;state.tankSolved=true;updateCount();updateObjective();setTimeout(()=>{showSprinklerStage();ui.sprinklerForm.querySelector("select")?.focus()},500)}
function submitSprinkler(event){event.preventDefault();const form=new FormData(ui.sprinklerForm),result=evaluateSprinklerGraph(form.get("period"),form.get("safeWindow"));ui.sprinklerFeedback.textContent=result.message;ui.sprinklerFeedback.className=`form-feedback ${result.ok?"is-success":"is-error"}`;if(!result.ok)return;state.sprinklerSolved=true;updateCount();updateObjective();setTimeout(()=>{ui.sprinklerStage.classList.add("is-hidden");ui.success.classList.remove("is-hidden");ui.sprinklerStep.className="is-complete";ui.activate.focus()},500)}
function showTankHint(){const hints=["그래프가 오른쪽으로 갈 때 선이 위로 가면 증가, 아래로 가면 감소, 수평이면 일정해.","감소 구간은 10~20분과 20~30분이야. 같은 10분 동안 몇 L씩 줄었는지 비교해 봐."];ui.tankFeedback.textContent=`힌트 · ${hints[Math.min(state.tankHintIndex,hints.length-1)]}`;ui.tankFeedback.className="form-feedback";state.tankHintIndex++}
function showSprinklerHint(){const hints=["0분의 관수량 모양이 다시 시작되는 시각을 찾아 두 시각의 차를 구해 봐.","현재 32분 뒤 그래프가 0에 닿은 다음, 수평으로 유지되는 첫 5분을 찾아봐."];ui.sprinklerFeedback.textContent=`힌트 · ${hints[Math.min(state.sprinklerHintIndex,hints.length-1)]}`;ui.sprinklerFeedback.className="form-feedback";state.sprinklerHintIndex++}
function activateSafeWindow(){closePanel(ui.panel);state.waterOff=true;updateObjective();showDialogue([{speaker:"관수 시스템",avatar:"관수",text:"35분 무분사 구간이 시작되었습니다. 다음 관수는 40분에 재개됩니다."},{speaker:"묘목 관리사",avatar:"관리",text:"묘목의 관수 일정은 그대로 유지됐어요. 물이 멈춘 동안 통로를 건너세요!"},{speaker:"WH",avatar:"WH",text:"그래프의 반복을 읽으니 기계를 억지로 멈추지 않고도 안전한 순간을 찾을 수 있었어."}])}
function updateCount(){ui.count.textContent=String(Number(state.tankSolved)+Number(state.sprinklerSolved))}
function updateObjective(){if(state.waterOff)ui.objective.textContent="물이 멈춘 통로를 지나 다음 숲길로 이동하자.";else if(state.sprinklerSolved)ui.objective.textContent="제어 모니터에서 35~40분 안전 시간을 실행하자.";else if(state.tankSolved)ui.objective.textContent="관수량 그래프의 반복 주기와 안전 시간을 찾자.";else if(state.operatorSpoken)ui.objective.textContent="제어 모니터에서 물탱크 변화 그래프를 확인하자.";else ui.objective.textContent="묘목 관리사에게 물줄기 상황을 물어보자."}

function showDialogue(lines,callback=null){clearMovement();state.dialogueQueue=[...lines];state.dialogueCallback=callback;ui.dialogue.classList.remove("is-hidden");showLine()}
function showLine(){const line=state.dialogueQueue[0];ui.speaker.textContent=line.speaker;ui.avatar.textContent=line.avatar;ui.avatar.style.background=line.avatar==="WH"?"#1b8f88":line.avatar==="관리"?"#6f8d48":"#247d74";ui.dialogueText.textContent=line.text;ui.dialogueNext.focus()}
function advanceDialogue(){if(ui.dialogue.classList.contains("is-hidden"))return;state.dialogueQueue.shift();if(state.dialogueQueue.length)return showLine();ui.dialogue.classList.add("is-hidden");const callback=state.dialogueCallback;state.dialogueCallback=null;if(callback)callback();canvas.focus()}
function openPanel(panel){clearMovement();panel.classList.remove("is-hidden");panel.querySelector("input,select,button")?.focus()}
function closePanel(panel){panel.classList.add("is-hidden");clearMovement();canvas.focus()}
function showToast(message){if(toastTimer)clearTimeout(toastTimer);ui.toast.textContent=message;ui.toast.classList.remove("is-hidden");toastTimer=setTimeout(()=>ui.toast.classList.add("is-hidden"),2500)}
function completeMap(){state.complete=true;ui.hud.classList.add("is-hidden");ui.prompt.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.complete.classList.remove("is-hidden");ui.replay.focus()}

function resize(){const rect=canvas.getBoundingClientRect(),density=Math.min(2,devicePixelRatio||1);viewWidth=Math.max(320,rect.width);viewHeight=Math.max(360,rect.height);groundY=Math.max(330,viewHeight*.76);canvas.width=Math.round(viewWidth*density);canvas.height=Math.round(viewHeight*density);ctx.setTransform(density,0,0,density,0,0)}
function updateCamera(dt){let target=state.playerX-viewWidth*.4;target=Math.max(0,Math.min(world.width-viewWidth,target));state.cameraX+=(target-state.cameraX)*(1-Math.exp(-4.5*dt))}
function screenX(x,parallax=1){return x-state.cameraX*parallax}
function draw(){const density=Math.min(2,devicePixelRatio||1);ctx.setTransform(density,0,0,density,0,0);ctx.clearRect(0,0,viewWidth,viewHeight);drawSky();drawGround();drawGreenhouses();drawNurseryRows();drawOperator();drawMonitor();drawIrrigation();drawMarkers();drawWH()}
function drawSky(){const gradient=ctx.createLinearGradient(0,0,0,groundY);gradient.addColorStop(0,"#9bd8d0");gradient.addColorStop(.72,"#e3e2ad");gradient.addColorStop(1,"#d8bd78");ctx.fillStyle=gradient;ctx.fillRect(0,0,viewWidth,viewHeight);ctx.fillStyle="#67966c";ctx.beginPath();ctx.moveTo(0,groundY-75);for(let x=-100;x<viewWidth+200;x+=210){const point=x-(state.cameraX*.14)%210;ctx.quadraticCurveTo(point+105,groundY-210,point+210,groundY-75)}ctx.lineTo(viewWidth,groundY);ctx.lineTo(0,groundY);ctx.fill()}
function drawGround(){ctx.fillStyle="#a58c5d";ctx.fillRect(0,groundY-24,viewWidth,48);ctx.fillStyle="#6d5b45";ctx.fillRect(0,groundY+24,viewWidth,viewHeight-groundY);ctx.fillStyle="#d7c58c";ctx.fillRect(0,groundY-9,viewWidth,18)}
function drawGreenhouses(){for(const x of [260,820,1530,2520]){const point=screenX(x,.82);ctx.strokeStyle="rgba(238,250,242,.7)";ctx.lineWidth=8;ctx.beginPath();ctx.arc(point,groundY-105,115,Math.PI,0);ctx.lineTo(point+115,groundY);ctx.moveTo(point-115,groundY-105);ctx.lineTo(point-115,groundY);ctx.stroke();ctx.fillStyle="rgba(218,244,230,.2)";ctx.beginPath();ctx.arc(point,groundY-105,110,Math.PI,0);ctx.lineTo(point+110,groundY);ctx.lineTo(point-110,groundY);ctx.fill()}}
function drawNurseryRows(){
  for(const bedX of NURSERY_BEDS){
    const point=screenX(bedX);if(point<-100||point>viewWidth+100)continue;
    ctx.fillStyle="#76563e";ctx.fillRect(point-58,groundY-21,116,20);
    ctx.fillStyle="rgba(67,103,56,.22)";ctx.beginPath();ctx.ellipse(point,groundY-27,64,12,0,0,Math.PI*2);ctx.fill();
  }
  for(const sapling of NURSERY_SAPLINGS){
    const point=screenX(sapling.x);if(point<-80||point>viewWidth+80)continue;
    if(assetManager.draw(ctx,sapling.key,{x:point,y:groundY-20,height:sapling.height,flipX:sapling.flipX,anchorX:.5,anchorY:1}))continue;
    ctx.fillStyle="#3e8058";ctx.beginPath();ctx.arc(point,groundY-48,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#5ea06d";ctx.beginPath();ctx.arc(point-8,groundY-61,12,0,Math.PI*2);ctx.fill();
  }
}
function drawOperator(){
  const point=screenX(world.operatorX);if(point<-80||point>viewWidth+80)return;
  if(assetManager.draw(ctx,"characters.saplingCaretaker",{x:point,y:groundY+4,height:178,anchorX:.5,anchorY:1}))return;
  drawPerson(world.operatorX,"#6f8d48","keeper")
}
function drawPerson(x,color,label){const point=screenX(x);if(point<-60||point>viewWidth+60)return;ctx.save();ctx.translate(point,groundY);ctx.strokeStyle="#28383a";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-8,-45);ctx.lineTo(-12,-3);ctx.moveTo(8,-45);ctx.lineTo(13,-3);ctx.stroke();ctx.fillStyle=color;roundRect(ctx,-28,-110,56,69,16);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 10px system-ui";ctx.textAlign="center";ctx.fillText(label,0,-72);ctx.fillStyle="#efc5a9";ctx.beginPath();ctx.arc(0,-138,27,0,Math.PI*2);ctx.fill();ctx.fillStyle="#496c43";ctx.beginPath();ctx.arc(0,-148,31,Math.PI,Math.PI*2);ctx.fill();ctx.restore()}
function drawMonitor(){
  const point=screenX(world.monitorX);if(point<-180||point>viewWidth+180)return;
  ctx.fillStyle="rgba(24,35,48,.16)";ctx.beginPath();ctx.ellipse(point,groundY+5,70,13,0,0,Math.PI*2);ctx.fill();
  if(assetManager.draw(ctx,"props.irrigationControlMonitor",{x:point,y:groundY+6,height:238,anchorX:.5,anchorY:1})){
    if(state.sprinklerSolved){ctx.fillStyle="#78d58a";ctx.beginPath();ctx.arc(point+56,groundY-38,10,0,Math.PI*2);ctx.fill();}
    return;
  }
  ctx.fillStyle="#315d59";roundRect(ctx,point-82,groundY-190,164,180,17);ctx.fill();ctx.fillStyle="#dff1e5";roundRect(ctx,point-65,groundY-170,130,91,9);ctx.fill();ctx.strokeStyle="#48a9c5";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(point-48,groundY-101);ctx.lineTo(point-24,groundY-145);ctx.lineTo(point,groundY-128);ctx.lineTo(point+25,groundY-155);ctx.lineTo(point+49,groundY-112);ctx.stroke();ctx.fillStyle="#f4c95f";ctx.beginPath();ctx.arc(point+45,groundY-42,9,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="900 11px system-ui";ctx.textAlign="center";ctx.fillText(state.sprinklerSolved?"OK":"CONTROL",point,groundY-20)
}
function drawIrrigation(){
  const point=screenX(world.sprinklerX),time=performance.now()/180,headY=groundY-176;
  ctx.fillStyle="rgba(24,35,48,.16)";ctx.beginPath();ctx.ellipse(point,groundY+6,86,14,0,0,Math.PI*2);ctx.fill();
  const drew=assetManager.draw(ctx,"props.automaticIrrigator",{x:point,y:groundY+6,height:236,anchorX:.5,anchorY:1,alpha:state.sprayLevel<.05?.92:1});
  if(!drew){ctx.fillStyle="#315d59";ctx.fillRect(point-9,groundY-137,18,137);roundRect(ctx,point-72,groundY-159,144,23,11);ctx.fill();ctx.fillStyle="#dce9e2";ctx.fillRect(point-145,groundY-8,290,16)}
  if(state.sprayLevel>.01){ctx.save();ctx.globalAlpha=.72*state.sprayLevel;ctx.strokeStyle="#67c5df";ctx.lineWidth=6;for(let index=-3;index<=3;index++){const sway=Math.sin(time+index)*8;ctx.beginPath();ctx.moveTo(point+index*20,headY);ctx.quadraticCurveTo(point+index*42+sway,groundY-235,point+index*78,groundY-52);ctx.stroke()}ctx.restore()}
  ctx.fillStyle=state.sprayLevel<.05?"#a9cb6d":"#f1bd55";ctx.beginPath();ctx.arc(point,headY-7,12,0,Math.PI*2);ctx.fill();
}
function drawMarkers(){if(!state.operatorSpoken)drawMarker(world.operatorX,state.nearby==="operator");else if(!state.waterOff)drawMarker(world.monitorX,state.nearby==="monitor")}
function drawMarker(x,active){const point=screenX(x),bounce=Math.sin(performance.now()/260)*4;if(point<-40||point>viewWidth+40)return;ctx.fillStyle=active?"#f1bd55":"#a8c96b";ctx.beginPath();ctx.arc(point,groundY-235+bounce,active?16:13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 18px system-ui";ctx.textAlign="center";ctx.fillText(active?"E":"!",point,groundY-228+bounce)}
function drawWH(){
  const point=screenX(state.playerX),moving=!paused()&&(keys.left||keys.right),step=moving?Math.sin(state.walkTime)*11:0,bounce=moving?Math.sin(state.walkTime*2)*2:0;
  if(assetManager.has("characters.wh")){
    ctx.fillStyle="rgba(24,35,48,.2)";ctx.beginPath();ctx.ellipse(point,groundY+5,36,10,0,0,Math.PI*2);ctx.fill();
    assetManager.draw(ctx,"characters.wh",{x:point,y:groundY+3+bounce,height:176,flipX:state.direction===-1,anchorX:.5,anchorY:1});
    return;
  }
  ctx.save();ctx.translate(point,groundY-2);ctx.scale(state.direction,1);ctx.strokeStyle="#1b2941";ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-8,-48);ctx.lineTo(-12-step*.55,-5);ctx.moveTo(9,-48);ctx.lineTo(14+step*.55,-5);ctx.stroke();ctx.fillStyle="#1b8f88";roundRect(ctx,-27,-119,58,78,20);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 12px system-ui";ctx.textAlign="center";ctx.fillText("WH",2,-76);ctx.fillStyle="#efc3a9";ctx.beginPath();ctx.arc(2,-151,35,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17223b";ctx.beginPath();ctx.arc(2,-162,36,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";for(const eye of [2,21]){ctx.beginPath();ctx.ellipse(eye,-151,8,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#126b68";ctx.beginPath();ctx.arc(eye+2,-150,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff"}ctx.restore()}
function roundRect(context,x,y,width,height,radius){radius=Math.min(radius,width/2,height/2);context.beginPath();context.moveTo(x+radius,y);context.arcTo(x+width,y,x+width,y+height,radius);context.arcTo(x+width,y+height,x,y+height,radius);context.arcTo(x,y+height,x,y,radius);context.arcTo(x,y,x+width,y,radius);context.closePath()}
