import { evaluateMixture, evaluateMonkeyDistribution } from "./ratio-logic.mjs";
import { assetManager } from "./asset-manager.mjs";

const canvas = document.querySelector("#map21-canvas");
const ctx = canvas.getContext("2d");
const ui = {
  hud: document.querySelector("#map21-hud"), objective: document.querySelector("#map21-objective"), progress: document.querySelector("#scene-progress"),
  prompt: document.querySelector("#map21-prompt"), promptText: document.querySelector("#map21-prompt-text"), toast: document.querySelector("#map21-toast"),
  start: document.querySelector("#map21-start"), startButton: document.querySelector("#map21-start-button"),
  dialogue: document.querySelector("#map21-dialogue"), avatar: document.querySelector("#map21-avatar"), speaker: document.querySelector("#map21-speaker"), dialogueText: document.querySelector("#map21-dialogue-text"), dialogueNext: document.querySelector("#map21-dialogue-next"),
  monkeyPanel: document.querySelector("#monkey-panel"), monkeyClose: document.querySelector("#monkey-close"), monkeyForm: document.querySelector("#monkey-form"), monkeyFeedback: document.querySelector("#monkey-feedback"), monkeyHint: document.querySelector("#monkey-hint"),
  mixturePanel: document.querySelector("#mixture-panel"), mixtureClose: document.querySelector("#mixture-close"), mixtureForm: document.querySelector("#mixture-form"), mixtureFeedback: document.querySelector("#mixture-feedback"), mixtureHint: document.querySelector("#mixture-hint"), tankFill: document.querySelector("#tank-fill"),
  complete: document.querySelector("#map21-complete"), replay: document.querySelector("#map21-replay"), next: document.querySelector("#map21-next"),
  touch: document.querySelector("#map21-touch"), left: document.querySelector("#map21-left"), right: document.querySelector("#map21-right"), interact: document.querySelector("#map21-interact")
};

const makeState = () => ({ started:false, playerX:180, direction:1, cameraX:0, rangerSpoken:false, monkeySolved:false, workerSpoken:false, mixtureSolved:false, cartOffset:0, cartMoving:false, nearby:null, dialogueQueue:[], dialogueCallback:null, monkeyHint:0, mixtureHint:0, complete:false, focusX:null, focusTimer:0, walkTime:0, lastTime:performance.now() });
let state = makeState();
let viewWidth=1280, viewHeight=720, groundY=540, toastTimer=null;
const keys={left:false,right:false};
const world={width:2920, monkeyBarrier:1280, exitBarrier:2470, interactions:[{id:"ranger",x:500,radius:85,label:"야생동물 관리사와 대화"},{id:"monkeys",x:1010,radius:115,label:"원숭이와 바나나 살펴보기"},{id:"worker",x:1600,radius:85,label:"산림 복원 작업자와 대화"},{id:"mixer",x:1990,radius:90,label:"영양액 혼합 장치 사용"}]};

resize(); assetManager.loadAll().catch((error)=>console.warn(error)); requestAnimationFrame(loop);
ui.startButton.addEventListener("click",startGame); ui.dialogueNext.addEventListener("click",advanceDialogue);
ui.monkeyClose.addEventListener("click",()=>closePanel(ui.monkeyPanel)); ui.mixtureClose.addEventListener("click",()=>closePanel(ui.mixturePanel));
ui.monkeyForm.addEventListener("submit",submitMonkey); ui.monkeyHint.addEventListener("click",showMonkeyHint);
ui.mixtureForm.addEventListener("submit",submitMixture); ui.mixtureHint.addEventListener("click",showMixtureHint);
ui.replay.addEventListener("click",resetGame);ui.next.addEventListener("click",()=>{window.location.href="./2map2.html"}); window.addEventListener("resize",resize); window.addEventListener("keydown",keyDown); window.addEventListener("keyup",keyUp); window.addEventListener("blur",clearMovement);
bindHold(ui.left,"left");bindHold(ui.right,"right");ui.interact.addEventListener("pointerdown",e=>{e.preventDefault();interact();});

function startGame(){state.started=true;state.lastTime=performance.now();ui.start.classList.add("is-hidden");ui.hud.classList.remove("is-hidden");if(matchMedia("(hover: none), (pointer: coarse)").matches)ui.touch.classList.remove("is-hidden");updateObjective();canvas.focus();}
function resetGame(){state=makeState();ui.complete.classList.add("is-hidden");ui.start.classList.remove("is-hidden");ui.hud.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.monkeyForm.reset();ui.mixtureForm.reset();ui.tankFill.style.height="12%";updateProgress();}
function keyDown(e){if(e.target instanceof HTMLInputElement)return;if(["ArrowLeft","ArrowRight","a","A","d","D","e","E","Enter"," "].includes(e.key))e.preventDefault();if(e.key==="Escape"){if(!ui.monkeyPanel.classList.contains("is-hidden"))closePanel(ui.monkeyPanel);else if(!ui.mixturePanel.classList.contains("is-hidden"))closePanel(ui.mixturePanel);else if(!ui.dialogue.classList.contains("is-hidden"))advanceDialogue();return;}if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=true;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=true;if((e.key==="Enter"||e.key===" ")&&!ui.dialogue.classList.contains("is-hidden"))return advanceDialogue();if(e.key.toLowerCase()==="e"||e.key==="Enter")interact();}
function keyUp(e){if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=false;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=false;}
function bindHold(button,direction){const start=e=>{e.preventDefault();keys[direction]=true},stop=e=>{e.preventDefault();keys[direction]=false};button.addEventListener("pointerdown",start);button.addEventListener("pointerup",stop);button.addEventListener("pointercancel",stop);button.addEventListener("pointerleave",stop);}
function clearMovement(){keys.left=false;keys.right=false;}
function loop(now){const dt=Math.min(.034,(now-state.lastTime)/1000||0);state.lastTime=now;update(dt);draw();requestAnimationFrame(loop);}
function update(dt){if(!state.started||state.complete)return;if(state.focusTimer>0){state.focusTimer-=dt;if(state.focusTimer<=0)state.focusX=null;}if(state.cartMoving){state.cartOffset=Math.min(520,state.cartOffset+220*dt);if(state.cartOffset>=520){state.cartMoving=false;showToast("급수 카트가 길을 비켰어. 다음 숲길로 이동하자!");updateObjective();}}
  if(!paused()){let d=0;if(keys.left)d--;if(keys.right)d++;if(d){state.playerX+=d*235*dt;state.direction=d;state.walkTime+=dt*10;const limit=!state.monkeySolved?world.monkeyBarrier:!state.mixtureSolved?world.exitBarrier:world.width-70;state.playerX=Math.max(70,Math.min(limit,state.playerX));}}
  updateNearby();updateCamera(dt);if(state.mixtureSolved&&state.cartOffset>=520&&state.playerX>2720)completeMap();}
function paused(){return!ui.dialogue.classList.contains("is-hidden")||!ui.monkeyPanel.classList.contains("is-hidden")||!ui.mixturePanel.classList.contains("is-hidden");}
function updateNearby(){if(paused()||state.cartMoving){state.nearby=null;ui.prompt.classList.add("is-hidden");return;}let nearest=null,dist=Infinity;for(const item of world.interactions){const d=Math.abs(state.playerX-item.x);if(d<=item.radius&&d<dist){nearest=item;dist=d;}}state.nearby=nearest?.id??null;if(nearest){ui.promptText.textContent=nearest.label;ui.prompt.classList.remove("is-hidden");}else ui.prompt.classList.add("is-hidden");}
function interact(){if(!state.started||paused()||state.cartMoving||!state.nearby)return;const id=state.nearby;if(id==="ranger"){if(!state.rangerSpoken)showDialogue([{speaker:"WH",avatar:"WH",text:"원숭이들이 싸우고 있어서 무서워서 지나갈 수가 없어요."},{speaker:"야생동물 관리사",avatar:"관리",text:"몸무게가 다른 원숭이에게 똑같이 주기보다, 몸무게의 비에 맞춰 나누면 다툼을 줄일 수 있어."},{speaker:"WH",avatar:"WH",text:"체중계 기록으로 바나나 30개를 공정하게 나눠 볼게요."}],()=>{state.rangerSpoken=true;updateObjective();});else showDialogue([{speaker:"야생동물 관리사",avatar:"관리",text:state.monkeySolved?"원숭이들이 차분해졌어. 숲 복원 구역으로 가도 안전해.":"몸무게 12 kg, 18 kg, 30 kg의 비를 가장 간단하게 나타내 봐."}]);return;}
  if(id==="monkeys"){if(!state.rangerSpoken){showToast("먼저 야생동물 관리사에게 도움을 구하자.");return;}if(state.monkeySolved)showToast("원숭이들은 각자의 바나나를 먹으며 쉬고 있어.");else openPanel(ui.monkeyPanel);return;}
  if(id==="worker"){if(!state.monkeySolved){showToast("원숭이들이 길을 막고 있어 아직 갈 수 없어.");return;}if(!state.workerSpoken)showDialogue([{speaker:"산림 복원 작업자",avatar:"복원",text:"묘목에 줄 영양액을 만들어야 카트를 옮길 수 있어. 원액과 물을 1:5로 섞어 총 24 L가 필요해."},{speaker:"WH",avatar:"WH",text:"비의 합으로 한 몫의 양을 구해서 밸브를 맞춰 볼게요."}],()=>{state.workerSpoken=true;updateObjective();});else showDialogue([{speaker:"산림 복원 작업자",avatar:"복원",text:state.mixtureSolved?"묘목이 물을 잘 흡수하고 있어. 고마워!":"원액과 물의 비 1:5, 전체 24 L를 기억해 줘."}]);return;}
  if(id==="mixer"){if(!state.workerSpoken){showToast("먼저 산림 복원 작업자에게 혼합 기준을 확인하자.");return;}if(state.mixtureSolved)showToast("영양액 혼합과 급수가 완료됐어.");else openPanel(ui.mixturePanel);}}
function submitMonkey(e){e.preventDefault();const f=new FormData(ui.monkeyForm);const result=evaluateMonkeyDistribution([f.get("ratioA"),f.get("ratioB"),f.get("ratioC")],[f.get("bananaA"),f.get("bananaB"),f.get("bananaC")]);feedback(ui.monkeyFeedback,result);if(!result.ok)return;state.monkeySolved=true;updateProgress();updateObjective();setTimeout(()=>{closePanel(ui.monkeyPanel);state.focusX=1010;state.focusTimer=2.5;showDialogue([{speaker:"야생동물 관리사",avatar:"관리",text:"6개, 9개, 15개! 몸무게의 비와 같아서 모두 납득했나 봐. 이제 안전하게 지나가도 돼."}]);},550);}
function submitMixture(e){e.preventDefault();const f=new FormData(ui.mixtureForm);const result=evaluateMixture(f.get("concentrate"),f.get("water"));feedback(ui.mixtureFeedback,result);if(!result.ok)return;state.mixtureSolved=true;ui.tankFill.style.height="88%";updateProgress();updateObjective();setTimeout(()=>{closePanel(ui.mixturePanel);state.cartMoving=true;state.focusX=2250;state.focusTimer=3;showDialogue([{speaker:"산림 복원 작업자",avatar:"복원",text:"원액 4 L와 물 20 L, 정확해! 급수를 시작하고 카트를 옮길게."}]);},550);}
function feedback(el,result){el.textContent=result.message;el.className=`form-feedback ${result.ok?"is-success":"is-error"}`;}
function showMonkeyHint(){const hints=["12:18:30의 세 수를 모두 6으로 나누어 봐.","가장 간단한 비 2:3:5의 합은 10이야.","바나나 30개를 10몫으로 나누면 한 몫은 3개야."];ui.monkeyFeedback.textContent=`힌트 · ${hints[Math.min(state.monkeyHint,hints.length-1)]}`;ui.monkeyFeedback.className="form-feedback";state.monkeyHint++;}
function showMixtureHint(){const hints=["원액과 물의 비 1:5의 합은 6이야.","전체 24 L를 6몫으로 나누면 한 몫은 4 L야.","원액은 1몫, 물은 5몫이야."];ui.mixtureFeedback.textContent=`힌트 · ${hints[Math.min(state.mixtureHint,hints.length-1)]}`;ui.mixtureFeedback.className="form-feedback";state.mixtureHint++;}
function updateProgress(){ui.progress.textContent=String(Number(state.monkeySolved)+Number(state.mixtureSolved));}
function updateObjective(){if(state.mixtureSolved)ui.objective.textContent="급수 카트가 이동한 뒤 열린 숲길로 가자.";else if(state.workerSpoken)ui.objective.textContent="영양 원액과 물을 1:5로 총 24 L 혼합하자.";else if(state.monkeySolved)ui.objective.textContent="숲 복원 구역의 작업자에게 말을 걸자.";else if(state.rangerSpoken)ui.objective.textContent="몸무게의 비에 따라 바나나 30개를 나누자.";else ui.objective.textContent="야생동물 관리사에게 상황을 물어보자.";}
function showDialogue(lines,callback=null){clearMovement();state.dialogueQueue=[...lines];state.dialogueCallback=callback;ui.dialogue.classList.remove("is-hidden");showLine();}
function showLine(){const line=state.dialogueQueue[0];ui.speaker.textContent=line.speaker;ui.avatar.textContent=line.avatar;ui.avatar.style.background=line.avatar==="WH"?"#1b8f88":line.avatar==="관리"?"#8a6547":"#4f8056";ui.dialogueText.textContent=line.text;ui.dialogueNext.focus();}
function advanceDialogue(){if(ui.dialogue.classList.contains("is-hidden"))return;state.dialogueQueue.shift();if(state.dialogueQueue.length)return showLine();ui.dialogue.classList.add("is-hidden");const cb=state.dialogueCallback;state.dialogueCallback=null;if(cb)cb();canvas.focus();}
function openPanel(panel){clearMovement();panel.classList.remove("is-hidden");panel.querySelector("input,button")?.focus();}function closePanel(panel){panel.classList.add("is-hidden");clearMovement();canvas.focus();}
function showToast(message){if(toastTimer)clearTimeout(toastTimer);ui.toast.textContent=message;ui.toast.classList.remove("is-hidden");toastTimer=setTimeout(()=>ui.toast.classList.add("is-hidden"),2500);}
function completeMap(){state.complete=true;ui.hud.classList.add("is-hidden");ui.prompt.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.complete.classList.remove("is-hidden");ui.replay.focus();}
function resize(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);viewWidth=Math.max(320,rect.width);viewHeight=Math.max(360,rect.height);groundY=Math.max(330,viewHeight*.76);canvas.width=Math.round(viewWidth*ratio);canvas.height=Math.round(viewHeight*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);}
function updateCamera(dt){let target=state.playerX-viewWidth*.4;if(state.focusX!==null)target=(state.playerX+state.focusX)/2-viewWidth/2;target=Math.max(0,Math.min(world.width-viewWidth,target));state.cameraX+=(target-state.cameraX)*(1-Math.exp(-4.5*dt));}function sx(x,p=1){return x-state.cameraX*p;}
function draw(){const ratio=Math.min(2,devicePixelRatio||1);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,viewWidth,viewHeight);drawSky();drawGround();drawBus();drawForest();drawPeople();drawMonkeys();drawRestoration();drawMarkers();drawWH();}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,groundY);g.addColorStop(0,"#95d4c1");g.addColorStop(.7,"#dfe4b7");g.addColorStop(1,"#dfc58b");ctx.fillStyle=g;ctx.fillRect(0,0,viewWidth,viewHeight);ctx.fillStyle="rgba(255,224,125,.9)";ctx.beginPath();ctx.arc(viewWidth-130,92,45,0,Math.PI*2);ctx.fill();ctx.fillStyle="#6fa05d";ctx.beginPath();ctx.moveTo(0,groundY-80);for(let x=-100;x<viewWidth+200;x+=180){const px=x-(state.cameraX*.15)%180;ctx.quadraticCurveTo(px+90,groundY-230,px+180,groundY-80)}ctx.lineTo(viewWidth,groundY);ctx.lineTo(0,groundY);ctx.fill();}
function drawGround(){ctx.fillStyle="#b9a57a";ctx.fillRect(0,groundY-25,viewWidth,50);ctx.fillStyle="#7d6a4e";ctx.fillRect(0,groundY+25,viewWidth,viewHeight-groundY);ctx.fillStyle="rgba(233,219,173,.45)";for(let x=-((state.cameraX)%120);x<viewWidth+120;x+=120)ctx.fillRect(x,groundY+75,70,4);}
function drawBus(){
  const x=sx(245);
  if(assetManager.draw(ctx,"vehicles.schoolTownShuttleBus",{x,y:groundY-24,height:245,anchorX:.5,anchorY:1}))return;
  const left=sx(30);ctx.fillStyle="#f2efe2";roundRect(ctx,left,groundY-205,420,175,40);ctx.fill();ctx.fillStyle="#4b9dab";ctx.fillRect(left+15,groundY-92,390,42);ctx.fillStyle="#a8d8db";for(let i=0;i<4;i++){roundRect(ctx,left+55+i*78,groundY-180,60,58,9);ctx.fill()}ctx.fillStyle="#273f4b";for(const wx of [left+95,left+335]){ctx.beginPath();ctx.arc(wx,groundY-35,32,0,Math.PI*2);ctx.fill()}ctx.fillStyle="#fff";ctx.font="900 12px system-ui";ctx.textAlign="center";ctx.fillText("SCHOOL TOWN",left+210,groundY-64);
}
function drawForest(){
  for(const x of [620,1350,1530,2600,2800])drawTree(x,1);
  const sign=sx(410);
  if(sign>-120&&sign<viewWidth+120){
    if(assetManager.draw(ctx,"props.signpost",{x:sign+4,y:groundY-18,height:156,anchorX:.5,anchorY:1})){
      drawSignLabel(sign+4,groundY-121,"\uD478\uB978\uC194\n\uC0DD\uD0DC\uC232");
    }else{
      ctx.fillStyle="#6b4d35";ctx.fillRect(sign,groundY-145,8,145);ctx.fillStyle="#315d46";roundRect(ctx,sign-65,groundY-165,138,42,8);ctx.fill();drawSignLabel(sign+4,groundY-139,"\uD478\uB978\uC194 \uC0DD\uD0DC\uC232");
    }
  }
}
function drawSignLabel(x,y,text){
  ctx.save();ctx.fillStyle="#23443a";ctx.font="900 12px Pretendard, 'Noto Sans KR', system-ui";ctx.textAlign="center";ctx.textBaseline="middle";
  const lines=String(text).split("\n");
  lines.forEach((line,index)=>ctx.fillText(line,x,y+index*14));
  ctx.restore();
}
function drawTree(x,scale){const px=sx(x);if(px<-100||px>viewWidth+100)return;if(assetManager.draw(ctx,"props.tree",{x:px,y:groundY+2,height:250*scale}))return;ctx.save();ctx.translate(px,groundY);ctx.scale(scale,scale);ctx.fillStyle="#735239";ctx.fillRect(-11,-180,22,180);ctx.fillStyle="#477b50";for(const [cx,cy,r] of [[0,-205,58],[-43,-170,42],[45,-172,46],[0,-252,40]]){ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill()}ctx.restore();}
function drawPeople(){drawWildlifeKeeper(500);if(state.monkeySolved)drawPerson(1600,"#4f8056");}
function drawWildlifeKeeper(x){const px=sx(x);if(px<-70||px>viewWidth+70)return;if(assetManager.draw(ctx,"characters.wildlifeKeeper",{x:px,y:groundY+3,height:178,anchorX:.5,anchorY:1}))return;drawPerson(x,"#8a6547");}
function drawPerson(x,color){const px=sx(x);if(px<-60||px>viewWidth+60)return;ctx.save();ctx.translate(px,groundY);ctx.strokeStyle="#303c3b";ctx.lineWidth=8;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-8,-44);ctx.lineTo(-12,-3);ctx.moveTo(8,-44);ctx.lineTo(13,-3);ctx.stroke();ctx.fillStyle=color;roundRect(ctx,-28,-108,56,68,15);ctx.fill();ctx.fillStyle="#ebc0a6";ctx.beginPath();ctx.arc(0,-136,27,0,Math.PI*2);ctx.fill();ctx.fillStyle="#3d332d";ctx.beginPath();ctx.arc(0,-143,28,Math.PI,Math.PI*2);ctx.fill();ctx.restore();}
function drawMonkeys(){const xs=[900,1020,1140],sizes=[.82,1,1.18];if(state.monkeySolved){ctx.strokeStyle="#735239";ctx.lineWidth=18;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(sx(820),groundY-145);ctx.quadraticCurveTo(sx(1030),groundY-205,sx(1230),groundY-170);ctx.stroke();}for(let i=0;i<3;i++){const px=sx(xs[i]);if(px<-90||px>viewWidth+90)continue;const y=state.monkeySolved?groundY-115-i*18:groundY;ctx.fillStyle="rgba(30,40,50,.16)";ctx.beginPath();ctx.ellipse(px,y+4,26*sizes[i],8*sizes[i],0,0,Math.PI*2);ctx.fill();if(assetManager.draw(ctx,"characters.monkey",{x:px,y:y+4,height:104*sizes[i]}))continue;ctx.save();ctx.translate(px,y);ctx.scale(sizes[i],sizes[i]);ctx.fillStyle="#765039";ctx.beginPath();ctx.arc(0,-85,32,0,Math.PI*2);ctx.fill();roundRect(ctx,-27,-60,54,58,20);ctx.fill();ctx.strokeStyle="#765039";ctx.lineWidth=10;ctx.beginPath();ctx.arc(26,-48,35,-1.2,1.6);ctx.stroke();ctx.fillStyle="#e4b48c";ctx.beginPath();ctx.arc(0,-82,21,0,Math.PI*2);ctx.fill();ctx.fillStyle="#2f2a28";ctx.beginPath();ctx.arc(-7,-86,3,0,Math.PI*2);ctx.arc(7,-86,3,0,Math.PI*2);ctx.fill();ctx.restore();}if(!state.monkeySolved)drawBananaPile(1020);}
function drawBananaPile(centerX){
  const x=sx(centerX);if(x<-160||x>viewWidth+160)return;
  const items=[
    {key:"props.bananaBunch",dx:-70,dy:-5,h:54},{key:"props.bananaSingle",dx:-22,dy:-2,h:31},{key:"props.bananaBunch",dx:31,dy:-12,h:48},{key:"props.bananaSingle",dx:78,dy:0,h:28},{key:"props.bananaSingle",dx:-105,dy:4,h:25}
  ];
  for(const item of items){
    if(assetManager.draw(ctx,item.key,{x:x+item.dx,y:groundY-4+item.dy,height:item.h,anchorX:.5,anchorY:1}))continue;
    ctx.fillStyle="#f0c84d";ctx.beginPath();ctx.ellipse(x+item.dx,groundY-9+item.dy,12,5,-.3,0,Math.PI*2);ctx.fill();
  }
}
function drawRestoration(){const x=sx(1860);if(x>-400&&x<viewWidth+500){for(let i=0;i<6;i++){const px=x+i*90;const h=(state.mixtureSolved?128:108)+(i%2)*10;if(assetManager.draw(ctx,"props.tree",{x:px,y:groundY+5,height:h,anchorX:.5,anchorY:1}))continue;ctx.strokeStyle="#4e7c4c";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(px,groundY);ctx.lineTo(px,groundY-62);ctx.stroke();ctx.fillStyle=state.mixtureSolved?"#79aa5a":"#9a9d62";ctx.beginPath();ctx.arc(px-13,groundY-52,18,0,Math.PI*2);ctx.arc(px+14,groundY-70,19,0,Math.PI*2);ctx.fill();}}
  const cart=sx(2180+state.cartOffset);ctx.fillStyle="#315d46";roundRect(ctx,cart-90,groundY-125,180,100,14);ctx.fill();ctx.fillStyle="#b7d670";ctx.beginPath();ctx.arc(cart-45,groundY-20,24,0,Math.PI*2);ctx.arc(cart+55,groundY-20,24,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eaf4dd";ctx.font="900 11px system-ui";ctx.textAlign="center";ctx.fillText(state.mixtureSolved?"SUPPLY":"MIX READY",cart,groundY-70);}
function drawMarkers(){if(!state.rangerSpoken)drawMarker(500,state.nearby==="ranger");else if(!state.monkeySolved)drawMarker(1010,state.nearby==="monkeys");else if(!state.workerSpoken)drawMarker(1600,state.nearby==="worker");else if(!state.mixtureSolved)drawMarker(1990,state.nearby==="mixer");}
function drawMarker(x,active){const px=sx(x),bob=Math.sin(performance.now()/260)*4;if(px<-40||px>viewWidth+40)return;ctx.fillStyle=active?"#e9a23c":"#83ba67";ctx.beginPath();ctx.arc(px,groundY-190+bob,active?16:13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 18px system-ui";ctx.textAlign="center";ctx.fillText(active?"E":"!",px,groundY-183+bob);}
function drawWH(){const x=sx(state.playerX),moving=!paused()&&(keys.left||keys.right),s=moving?Math.sin(state.walkTime)*11:0,b=moving?Math.sin(state.walkTime*2)*2:0;if(assetManager.has("characters.wh")){ctx.fillStyle="rgba(24,35,48,.2)";ctx.beginPath();ctx.ellipse(x,groundY+5,36,10,0,0,Math.PI*2);ctx.fill();assetManager.draw(ctx,"characters.wh",{x,y:groundY+3+b,height:176,flipX:state.direction===-1});return;}ctx.save();ctx.translate(x,groundY-2+b);ctx.scale(state.direction,1);ctx.strokeStyle="#1b2941";ctx.lineWidth=9;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-8,-48);ctx.lineTo(-12-s*.55,-5);ctx.moveTo(9,-48);ctx.lineTo(14+s*.55,-5);ctx.stroke();ctx.fillStyle="#1b8f88";roundRect(ctx,-27,-119,58,78,20);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 12px system-ui";ctx.textAlign="center";ctx.save();ctx.scale(state.direction,1);ctx.fillText("WH",2*state.direction,-76);ctx.restore();ctx.fillStyle="#efc3a9";ctx.beginPath();ctx.arc(2,-151,35,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17223b";ctx.beginPath();ctx.arc(2,-162,36,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";for(const ex of [2,21]){ctx.beginPath();ctx.ellipse(ex,-151,8,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#126b68";ctx.beginPath();ctx.arc(ex+2,-150,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";}ctx.restore();}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
