import { evaluateDiscount, evaluateProfit, evaluateSalary } from "./percent-logic.mjs";
import { assetManager } from "./asset-manager.mjs";

const canvas=document.querySelector("#map22-canvas"),ctx=canvas.getContext("2d");
const ui={hud:document.querySelector("#map22-hud"),objective:document.querySelector("#map22-objective"),count:document.querySelector("#evidence-count"),prompt:document.querySelector("#map22-prompt"),promptText:document.querySelector("#map22-prompt-text"),toast:document.querySelector("#map22-toast"),start:document.querySelector("#map22-start"),startButton:document.querySelector("#map22-start-button"),dialogue:document.querySelector("#map22-dialogue"),avatar:document.querySelector("#map22-avatar"),speaker:document.querySelector("#map22-speaker"),dialogueText:document.querySelector("#map22-dialogue-text"),dialogueNext:document.querySelector("#map22-dialogue-next"),panel:document.querySelector("#document-panel"),panelClose:document.querySelector("#document-close"),kicker:document.querySelector("#document-kicker"),title:document.querySelector("#document-title"),stamp:document.querySelector("#document-stamp"),factsTitle:document.querySelector("#document-facts-title"),facts:document.querySelector("#document-facts"),rule:document.querySelector("#document-rule"),question:document.querySelector("#document-question"),inputs:document.querySelector("#document-inputs"),form:document.querySelector("#document-form"),feedback:document.querySelector("#document-feedback"),hint:document.querySelector("#document-hint"),resolution:document.querySelector("#resolution-panel"),resolutionClose:document.querySelector("#resolution-close"),resolve:document.querySelector("#resolve-dispute"),complete:document.querySelector("#map22-complete"),replay:document.querySelector("#map22-replay"),next:document.querySelector("#map22-next"),touch:document.querySelector("#map22-touch"),left:document.querySelector("#map22-left"),right:document.querySelector("#map22-right"),interact:document.querySelector("#map22-interact")};

const documents={
 salary:{title:"월급 인상 제안서",kicker:"SALARY REVIEW",factsTitle:"작업자 월급 변경",facts:[["인상 전 월급","2,500,000원"],["제안 월급","2,700,000원"],["약속한 인상률","10%"]],rule:"인상률 = 인상액 ÷ 인상 전 금액 × 100",question:"실제 인상률과 약속한 10%를 적용한 월급을 구하세요.",inputs:[{name:"rate",label:"실제 인상률",unit:"%"},{name:"promisedPay",label:"10% 인상 적용 월급",unit:"원"}],evaluate:v=>evaluateSalary(v.rate,v.promisedPay),hints:["인상액은 2,700,000 - 2,500,000이야.","인상률의 기준은 인상 후가 아니라 인상 전 월급이야.","10%는 소수로 0.10이야. 기존 월급의 10%를 더해 봐."]},
 discount:{title:"안전장비 구매 견적서",kicker:"SAFETY PURCHASE",factsTitle:"보호장비 공동 구매",facts:[["할인 전 표시 가격","500,000원"],["할인 적용 가격","425,000원"],["구매 품목","동일 안전장비 전체"]],rule:"할인율 = 할인 금액 ÷ 할인 전 가격 × 100",question:"할인 금액과 할인율을 구하세요.",inputs:[{name:"amount",label:"할인 금액",unit:"원"},{name:"rate",label:"할인율",unit:"%"}],evaluate:v=>evaluateDiscount(v.amount,v.rate),hints:["할인 금액은 할인 전 가격에서 할인 적용 가격을 빼서 구해.","할인율의 기준은 할인 후가 아니라 할인 전 표시 가격이야.","75,000 ÷ 500,000 × 100을 계산해 봐."]},
 profit:{title:"간벌 사업 정산서",kicker:"PROJECT SETTLEMENT",factsTitle:"산림 관리 사업 손익",facts:[["작업 원가","4,000,000원"],["부산물 판매 수익","4,800,000원"],["손익률 기준","작업 원가"]],rule:"이 문제의 손익률 = 손익 ÷ 원가 × 100",question:"이익과 원가 기준 손익률을 구하세요.",inputs:[{name:"profit",label:"이익",unit:"원"},{name:"rate",label:"손익률",unit:"%"}],evaluate:v=>evaluateProfit(v.profit,v.rate),hints:["이익은 판매 수익에서 작업 원가를 빼서 구해.","이 문제에서는 판매 수익이 아니라 원가가 손익률의 기준이야.","800,000 ÷ 4,000,000 × 100을 계산해 봐."]}
};

const positions={salary:900,discount:1280,profit:1660};
const makeState=()=>({started:false,playerX:180,direction:1,cameraX:0,coordinatorSpoken:false,solved:new Set(),current:null,hints:{salary:0,discount:0,profit:0},nearby:null,dialogueQueue:[],dialogueCallback:null,resolved:false,logsOffset:0,logsMoving:false,focusX:null,focusTimer:0,complete:false,walkTime:0,lastTime:performance.now()});let state=makeState(),viewWidth=1280,viewHeight=720,groundY=540,toastTimer=null;const keys={left:false,right:false};
const world={width:2920,interactions:[{id:"coordinator",x:500,radius:85,label:"현장 조정 담당자와 대화"},...Object.keys(documents).map(id=>({id,x:positions[id],radius:78,label:`${documents[id].title} 검토`})),{id:"table",x:2070,radius:95,label:"협상 테이블에 근거 제시"}]};
resize();assetManager.loadAll().catch((error)=>console.warn(error));requestAnimationFrame(loop);
ui.startButton.addEventListener("click",startGame);ui.dialogueNext.addEventListener("click",advanceDialogue);ui.panelClose.addEventListener("click",()=>closePanel(ui.panel));ui.form.addEventListener("submit",submitDocument);ui.hint.addEventListener("click",showHint);ui.resolutionClose.addEventListener("click",()=>closePanel(ui.resolution));ui.resolve.addEventListener("click",resolveDispute);ui.replay.addEventListener("click",resetGame);ui.next.addEventListener("click",()=>{window.location.href="./2map3.html"});window.addEventListener("resize",resize);window.addEventListener("keydown",keyDown);window.addEventListener("keyup",keyUp);window.addEventListener("blur",clearMovement);bindHold(ui.left,"left");bindHold(ui.right,"right");ui.interact.addEventListener("pointerdown",e=>{e.preventDefault();interact();});
function startGame(){state.started=true;state.lastTime=performance.now();ui.start.classList.add("is-hidden");ui.hud.classList.remove("is-hidden");if(matchMedia("(hover: none), (pointer: coarse)").matches)ui.touch.classList.remove("is-hidden");updateObjective();canvas.focus();}function resetGame(){state=makeState();ui.complete.classList.add("is-hidden");ui.start.classList.remove("is-hidden");ui.hud.classList.add("is-hidden");ui.touch.classList.add("is-hidden");updateCount();}
function keyDown(e){if(e.target instanceof HTMLInputElement)return;if(["ArrowLeft","ArrowRight","a","A","d","D","e","E","Enter"," "].includes(e.key))e.preventDefault();if(e.key==="Escape"){if(!ui.resolution.classList.contains("is-hidden"))closePanel(ui.resolution);else if(!ui.panel.classList.contains("is-hidden"))closePanel(ui.panel);else if(!ui.dialogue.classList.contains("is-hidden"))advanceDialogue();return}if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=true;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=true;if((e.key==="Enter"||e.key===" ")&&!ui.dialogue.classList.contains("is-hidden"))return advanceDialogue();if(e.key.toLowerCase()==="e"||e.key==="Enter")interact();}function keyUp(e){if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=false;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=false;}function bindHold(b,d){const s=e=>{e.preventDefault();keys[d]=true},t=e=>{e.preventDefault();keys[d]=false};b.addEventListener("pointerdown",s);b.addEventListener("pointerup",t);b.addEventListener("pointercancel",t);b.addEventListener("pointerleave",t)}function clearMovement(){keys.left=false;keys.right=false}
function loop(now){const dt=Math.min(.034,(now-state.lastTime)/1000||0);state.lastTime=now;update(dt);draw();requestAnimationFrame(loop)}function update(dt){if(!state.started||state.complete)return;if(state.focusTimer>0){state.focusTimer-=dt;if(state.focusTimer<=0)state.focusX=null}if(state.logsMoving){state.logsOffset=Math.min(520,state.logsOffset+220*dt);if(state.logsOffset>=520){state.logsMoving=false;showToast("운반 장비와 안전 펜스가 이동했어. 숲길이 열렸어!")}}if(!paused()){let d=0;if(keys.left)d--;if(keys.right)d++;if(d){state.playerX+=d*235*dt;state.direction=d;state.walkTime+=dt*10;const limit=state.resolved?world.width-70:2440;state.playerX=Math.max(70,Math.min(limit,state.playerX))}}updateNearby();updateCamera(dt);if(state.resolved&&state.logsOffset>=520&&state.playerX>2720)completeMap()}
function paused(){return!ui.dialogue.classList.contains("is-hidden")||!ui.panel.classList.contains("is-hidden")||!ui.resolution.classList.contains("is-hidden")}function updateNearby(){if(paused()||state.logsMoving){state.nearby=null;ui.prompt.classList.add("is-hidden");return}let n=null,dist=Infinity;for(const item of world.interactions){const d=Math.abs(state.playerX-item.x);if(d<=item.radius&&d<dist){n=item;dist=d}}state.nearby=n?.id??null;if(n){ui.promptText.textContent=n.label;ui.prompt.classList.remove("is-hidden")}else ui.prompt.classList.add("is-hidden")}
function interact(){if(!state.started||paused()||state.logsMoving||!state.nearby)return;const id=state.nearby;if(id==="coordinator"){if(!state.coordinatorSpoken)showDialogue([{speaker:"작업자",avatar:"작업",text:"약속은 10% 인상이었는데 250만 원에서 270만 원이면 정말 10%가 맞나요?"},{speaker:"현장 상사",avatar:"상사",text:"20만 원이나 올랐으니 10% 정도라고 생각했는데… 계산을 다시 확인해야겠군."},{speaker:"현장 조정 담당자",avatar:"조정",text:"급여, 안전장비와 사업 정산 자료의 기준을 정확히 확인해 주세요. 계산 뒤에는 당사자들이 다시 협상할 겁니다."}],()=>{state.coordinatorSpoken=true;updateObjective()});else showDialogue([{speaker:"현장 조정 담당자",avatar:"조정",text:state.solved.size<3?`확인해야 할 문서가 ${3-state.solved.size}개 남았습니다.`:"세 근거가 모였습니다. 협상 테이블에서 함께 확인해 주세요."}]);return}if(!state.coordinatorSpoken){showToast("먼저 현장 조정 담당자에게 상황을 확인하자.");return}if(documents[id]){if(state.solved.has(id))showToast(`${documents[id].title}는 이미 검토했어.`);else openDocument(id);return}if(id==="table"){if(state.solved.size<3){showToast(`협상에 필요한 근거가 ${3-state.solved.size}개 부족해.`);return}openPanel(ui.resolution)}}
function openDocument(id){const d=documents[id];state.current=id;ui.kicker.textContent=d.kicker;ui.title.textContent=d.title;ui.stamp.textContent="검토 전";ui.factsTitle.textContent=d.factsTitle;ui.facts.innerHTML=d.facts.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join("");ui.rule.textContent=d.rule;ui.question.textContent=d.question;ui.inputs.innerHTML=d.inputs.map(i=>`<label>${i.label}<div class="money-input"><input name="${i.name}" inputmode="numeric" autocomplete="off"/><span>${i.unit}</span></div></label>`).join("");ui.feedback.textContent="비율을 계산할 때 무엇이 기준인지 먼저 확인해.";ui.feedback.className="form-feedback";openPanel(ui.panel);setTimeout(()=>ui.inputs.querySelector("input")?.focus(),0)}
function submitDocument(e){e.preventDefault();const d=documents[state.current],f=Object.fromEntries(new FormData(ui.form));const result=d.evaluate(f);ui.feedback.textContent=result.message;ui.feedback.className=`form-feedback ${result.ok?"is-success":"is-error"}`;if(!result.ok)return;ui.stamp.textContent="검토 완료 ✓";state.solved.add(state.current);updateCount();updateObjective();const title=d.title;setTimeout(()=>{closePanel(ui.panel);showToast(`${title} 근거 카드 확보 · ${state.solved.size}/3`);if(state.solved.size===3)showDialogue([{speaker:"현장 조정 담당자",avatar:"조정",text:"세 비율의 기준이 모두 확인됐습니다. 이제 협상 테이블에서 같은 자료를 함께 봅시다."}])},550)}function showHint(){const d=documents[state.current],i=Math.min(state.hints[state.current],d.hints.length-1);ui.feedback.textContent=`힌트 · ${d.hints[i]}`;ui.feedback.className="form-feedback";state.hints[state.current]++}
function updateCount(){ui.count.textContent=String(state.solved.size)}function updateObjective(){if(state.resolved)ui.objective.textContent="이동한 안전 펜스 너머 숲길로 가자.";else if(state.solved.size===3)ui.objective.textContent="협상 테이블에서 세 근거를 함께 확인하자.";else if(state.coordinatorSpoken)ui.objective.textContent=`재무 문서의 백분율 확인 ${state.solved.size}/3`;else ui.objective.textContent="현장 조정 담당자에게 상황을 물어보자."}
function resolveDispute(){closePanel(ui.resolution);showDialogue([{speaker:"WH",avatar:"WH",text:"실제 제안은 8% 인상이고, 약속한 10%를 적용하면 275만 원이에요. 할인율은 15%, 원가 기준 손익률은 20%예요."},{speaker:"현장 상사",avatar:"상사",text:"인상률 계산이 잘못됐습니다. 약속한 10% 기준으로 제안서를 수정하고 안전 예산은 그대로 지키겠습니다."},{speaker:"작업자",avatar:"작업",text:"확인된 자료를 바탕으로 다시 협상하겠습니다. 합의가 끝나면 안전하게 작업을 재개할게요."}],()=>{state.resolved=true;state.logsMoving=true;state.focusX=2420;state.focusTimer=3;updateObjective()})}
function showDialogue(lines,cb=null){clearMovement();state.dialogueQueue=[...lines];state.dialogueCallback=cb;ui.dialogue.classList.remove("is-hidden");showLine()}function showLine(){const l=state.dialogueQueue[0];ui.speaker.textContent=l.speaker;ui.avatar.textContent=l.avatar;ui.avatar.style.background=l.avatar==="WH"?"#1b8f88":l.avatar==="작업"?"#c87a38":l.avatar==="상사"?"#596a42":"#4d5a38";ui.dialogueText.textContent=l.text;ui.dialogueNext.focus()}function advanceDialogue(){if(ui.dialogue.classList.contains("is-hidden"))return;state.dialogueQueue.shift();if(state.dialogueQueue.length)return showLine();ui.dialogue.classList.add("is-hidden");const cb=state.dialogueCallback;state.dialogueCallback=null;if(cb)cb();canvas.focus()}
function openPanel(p){clearMovement();p.classList.remove("is-hidden");p.querySelector("input,button")?.focus()}function closePanel(p){p.classList.add("is-hidden");clearMovement();canvas.focus()}function showToast(m){if(toastTimer)clearTimeout(toastTimer);ui.toast.textContent=m;ui.toast.classList.remove("is-hidden");toastTimer=setTimeout(()=>ui.toast.classList.add("is-hidden"),2500)}function completeMap(){state.complete=true;ui.hud.classList.add("is-hidden");ui.prompt.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.complete.classList.remove("is-hidden");ui.replay.focus()}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);viewWidth=Math.max(320,r.width);viewHeight=Math.max(360,r.height);groundY=Math.max(330,viewHeight*.76);canvas.width=Math.round(viewWidth*d);canvas.height=Math.round(viewHeight*d);ctx.setTransform(d,0,0,d,0,0)}function updateCamera(dt){let t=state.playerX-viewWidth*.4;if(state.focusX!==null)t=(state.playerX+state.focusX)/2-viewWidth/2;t=Math.max(0,Math.min(world.width-viewWidth,t));state.cameraX+=(t-state.cameraX)*(1-Math.exp(-4.5*dt))}function sx(x,p=1){return x-state.cameraX*p}
function draw(){const d=Math.min(2,devicePixelRatio||1);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,viewWidth,viewHeight);drawSky();drawGround();drawForest();drawPeople();drawStations();drawLogs();drawMarkers();drawWH()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,groundY);g.addColorStop(0,"#a8c9ad");g.addColorStop(.7,"#d8d3a7");g.addColorStop(1,"#d4b87d");ctx.fillStyle=g;ctx.fillRect(0,0,viewWidth,viewHeight);ctx.fillStyle="#738a5b";ctx.beginPath();ctx.moveTo(0,groundY-80);for(let x=-100;x<viewWidth+200;x+=190){const p=x-(state.cameraX*.15)%190;ctx.quadraticCurveTo(p+95,groundY-230,p+190,groundY-80)}ctx.lineTo(viewWidth,groundY);ctx.lineTo(0,groundY);ctx.fill()}
function drawGround(){ctx.fillStyle="#b8a174";ctx.fillRect(0,groundY-25,viewWidth,50);ctx.fillStyle="#756249";ctx.fillRect(0,groundY+25,viewWidth,viewHeight-groundY)}function drawForest(){
  for(const [x,height,alpha] of [[80,265,.92],[320,310,1],[700,285,.95],[1100,320,1],[1500,300,.95],[1900,325,1],[2700,295,.95]])drawTree(x,height,alpha)
}
function drawTree(x,height=300,alpha=1){
  const p=sx(x);if(p<-160||p>viewWidth+160)return;
  if(assetManager.draw(ctx,"props.tree",{x:p,y:groundY+6,height,alpha,anchorX:.5,anchorY:1}))return;
  ctx.fillStyle="#725039";ctx.fillRect(p-11,groundY-210,22,210);ctx.fillStyle="#526f45";for(const [a,b,r] of [[0,-235,55],[-38,-205,40],[40,-205,43],[0,-275,38]]){ctx.beginPath();ctx.arc(p+a,groundY+b,r,0,Math.PI*2);ctx.fill()}
}
function drawPeople(){
  drawWorker(500,"worker01",.96);
  drawWorker(610,"worker02",.91);
  drawWorker(690,"worker03",.93,true);
  drawWorker(770,"worker04",.92);
}
function drawWorker(x,workerKey,scale=1,flipX=false){
  const p=sx(x);if(p<-70||p>viewWidth+70)return;
  const height=178*scale;
  if(assetManager.draw(ctx,`characters.forestWorkers.${workerKey}`,{x:p,y:groundY+4,height,flipX,anchorX:.5,anchorY:1}))return;
  drawPerson(x,"#c87a38");
}
function drawPerson(x,color){const p=sx(x);if(p<-50||p>viewWidth+50)return;ctx.save();ctx.translate(p,groundY);ctx.strokeStyle="#343b35";ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-8,-44);ctx.lineTo(-12,-3);ctx.moveTo(8,-44);ctx.lineTo(13,-3);ctx.stroke();ctx.fillStyle=color;roundRect(ctx,-27,-107,54,67,15);ctx.fill();ctx.fillStyle="#efc4a8";ctx.beginPath();ctx.arc(0,-135,26,0,Math.PI*2);ctx.fill();ctx.fillStyle="#e89b3f";ctx.beginPath();ctx.arc(0,-145,30,Math.PI,Math.PI*2);ctx.fill();ctx.restore()}
function drawStations(){
  for(const [id,x] of Object.entries(positions)){
    const p=sx(x),done=state.solved.has(id),assetKey=stationAssetKey(id);
    if(p<-130||p>viewWidth+130)continue;
    ctx.fillStyle="rgba(31,38,30,.16)";ctx.beginPath();ctx.ellipse(p,groundY+6,54,12,0,0,Math.PI*2);ctx.fill();
    const drawn=assetManager.draw(ctx,assetKey,{x:p,y:groundY+6,height:184,anchorX:.5,anchorY:1,alpha:done?.92:1});
    if(!drawn){ctx.fillStyle="#67543f";roundRect(ctx,p-52,groundY-135,104,125,11);ctx.fill();ctx.fillStyle=done?"#9fbd71":"#eee2c8";ctx.fillRect(p-39,groundY-121,78,72)}
    drawStationBadge(p,groundY-104,id,done);
  }
}
function stationAssetKey(id){return id==="salary"?"props.salaryProposalEasel":id==="discount"?"props.safetyQuoteEasel":"props.businessProfitEasel"}
function drawStationBadge(x,y,id,done){
  if(!done)return;
  ctx.save();ctx.textAlign="center";ctx.font="900 13px system-ui";ctx.lineWidth=5;ctx.strokeStyle="rgba(255,255,255,.9)";ctx.fillStyle="#2f7a50";ctx.strokeText("OK",x+38,y+36);ctx.fillText("OK",x+38,y+36);ctx.restore();
}
function drawLogs(){const p=sx(2350+state.logsOffset);const gateKey=state.resolved?"props.openIronGate":"props.closedIronGate";if(assetManager.draw(ctx,gateKey,{x:p,y:groundY+8,height:232}))return;for(let i=0;i<4;i++){ctx.fillStyle="#966a47";roundRect(ctx,p-100+i*23,groundY-50-i*34,220,32,16);ctx.fill();ctx.strokeStyle="#5f432f";ctx.lineWidth=4;ctx.stroke()}ctx.fillStyle="#df863f";ctx.fillRect(p-120,groundY-150,18,150);ctx.fillRect(p+130,groundY-150,18,150);ctx.fillRect(p-120,groundY-150,268,15)}function drawMarkers(){if(!state.coordinatorSpoken)drawMarker(500,state.nearby==="coordinator");else{for(const [id,x] of Object.entries(positions))if(!state.solved.has(id))drawMarker(x,state.nearby===id);if(state.solved.size===3&&!state.resolved)drawMarker(2070,state.nearby==="table")}}function drawMarker(x,a){const p=sx(x),b=Math.sin(performance.now()/260)*4;if(p<-40||p>viewWidth+40)return;ctx.fillStyle=a?"#df863f":"#9fbd71";ctx.beginPath();ctx.arc(p,groundY-185+b,a?16:13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 18px system-ui";ctx.textAlign="center";ctx.fillText(a?"E":"!",p,groundY-178+b)}
function drawWH(){
  const p=sx(state.playerX),m=!paused()&&(keys.left||keys.right),s=m?Math.sin(state.walkTime)*11:0,b=m?Math.sin(state.walkTime*2)*2:0;
  if(assetManager.has("characters.wh")){
    ctx.fillStyle="rgba(24,35,48,.2)";ctx.beginPath();ctx.ellipse(p,groundY+5,36,10,0,0,Math.PI*2);ctx.fill();
    assetManager.draw(ctx,"characters.wh",{x:p,y:groundY+3+b,height:176,flipX:state.direction===-1,anchorX:.5,anchorY:1});
    return;
  }
  ctx.save();ctx.translate(p,groundY-2);ctx.scale(state.direction,1);ctx.strokeStyle="#1b2941";ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-8,-48);ctx.lineTo(-12-s*.55,-5);ctx.moveTo(9,-48);ctx.lineTo(14+s*.55,-5);ctx.stroke();ctx.fillStyle="#1b8f88";roundRect(ctx,-27,-119,58,78,20);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 12px system-ui";ctx.textAlign="center";ctx.fillText("WH",2,-76);ctx.fillStyle="#efc3a9";ctx.beginPath();ctx.arc(2,-151,35,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17223b";ctx.beginPath();ctx.arc(2,-162,36,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";for(const e of [2,21]){ctx.beginPath();ctx.ellipse(e,-151,8,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#126b68";ctx.beginPath();ctx.arc(e+2,-150,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff"}ctx.restore()}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
