import { ATM_FEE_ROWS, evaluateAtmPlan } from "./atm-logic.mjs";
import { assetManager } from "./asset-manager.mjs";

const canvas=document.querySelector("#map23-canvas"),ctx=canvas.getContext("2d");
const ui={hud:document.querySelector("#map23-hud"),objective:document.querySelector("#map23-objective"),wallet:document.querySelector("#wallet-cash"),prompt:document.querySelector("#map23-prompt"),promptText:document.querySelector("#map23-prompt-text"),toast:document.querySelector("#map23-toast"),start:document.querySelector("#map23-start"),startButton:document.querySelector("#map23-start-button"),dialogue:document.querySelector("#map23-dialogue"),avatar:document.querySelector("#map23-avatar"),speaker:document.querySelector("#map23-speaker"),dialogueText:document.querySelector("#map23-dialogue-text"),dialogueNext:document.querySelector("#map23-dialogue-next"),panel:document.querySelector("#atm-panel"),close:document.querySelector("#atm-close"),problem:document.querySelector("#atm-problem"),success:document.querySelector("#atm-success"),tableBody:document.querySelector("#fee-table-body"),form:document.querySelector("#atm-form"),feedback:document.querySelector("#atm-feedback"),hint:document.querySelector("#atm-hint"),confirm:document.querySelector("#confirm-withdrawal"),calculatorDisplay:document.querySelector("#calculator-display"),calculatorPad:document.querySelector("#calculator-pad"),complete:document.querySelector("#map23-complete"),replay:document.querySelector("#map23-replay"),next:document.querySelector("#map23-next"),touch:document.querySelector("#map23-touch"),left:document.querySelector("#map23-left"),right:document.querySelector("#map23-right"),interact:document.querySelector("#map23-interact")};
const makeState=()=>({started:false,playerX:180,direction:1,cameraX:0,atmSeen:false,planSolved:false,transactionDone:false,nearby:null,hintIndex:0,dialogueQueue:[],dialogueCallback:null,cashAnim:0,complete:false,walkTime:0,lastTime:performance.now()});let state=makeState(),viewWidth=1280,viewHeight=720,groundY=540,toastTimer=null,calculatorTokens=[];const keys={left:false,right:false},world={width:2650,atmX:1280,interactions:[{id:"atm",x:1280,radius:120,label:"수수료표와 ATM 확인"}]};
ui.tableBody.innerHTML=ATM_FEE_ROWS.map(row=>`<tr><td>${row.label}</td><td>${row.rate.toFixed(2)}%</td><td>${money(row.extraFee)}</td></tr>`).join("");resize();assetManager.loadAll().catch((error)=>console.warn(error));requestAnimationFrame(loop);
ui.startButton.addEventListener("click",startGame);ui.dialogueNext.addEventListener("click",advanceDialogue);ui.close.addEventListener("click",()=>closePanel(ui.panel));ui.form.addEventListener("submit",submitPlan);ui.hint.addEventListener("click",showHint);ui.confirm.addEventListener("click",completeTransaction);ui.calculatorPad.addEventListener("click",useCalculator);ui.replay.addEventListener("click",resetGame);ui.next.addEventListener("click",()=>{window.location.href="./2map4.html"});window.addEventListener("resize",resize);window.addEventListener("keydown",keyDown);window.addEventListener("keyup",keyUp);window.addEventListener("blur",clearMovement);bindHold(ui.left,"left");bindHold(ui.right,"right");ui.interact.addEventListener("pointerdown",e=>{e.preventDefault();interact()});
function money(v){return `${v.toLocaleString("ko-KR")}원`}function startGame(){state.started=true;state.lastTime=performance.now();ui.start.classList.add("is-hidden");ui.hud.classList.remove("is-hidden");if(matchMedia("(hover: none),(pointer: coarse)").matches)ui.touch.classList.remove("is-hidden");canvas.focus()}function resetGame(){state=makeState();ui.form.reset();ui.feedback.textContent="";ui.problem.classList.remove("is-hidden");ui.success.classList.add("is-hidden");ui.complete.classList.add("is-hidden");ui.start.classList.remove("is-hidden");ui.hud.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.wallet.textContent="350,000원";resetCalculator()}
function keyDown(e){if(e.target.matches?.("input,select,button"))return;if(["ArrowLeft","ArrowRight","a","A","d","D","e","E","Enter"," "].includes(e.key))e.preventDefault();if(e.key==="Escape"){if(!ui.panel.classList.contains("is-hidden"))closePanel(ui.panel);else if(!ui.dialogue.classList.contains("is-hidden"))advanceDialogue();return}if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=true;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=true;if((e.key==="Enter"||e.key===" ")&&!ui.dialogue.classList.contains("is-hidden"))return advanceDialogue();if(e.key.toLowerCase()==="e"||e.key==="Enter")interact()}function keyUp(e){if(e.key==="ArrowLeft"||e.key.toLowerCase()==="a")keys.left=false;if(e.key==="ArrowRight"||e.key.toLowerCase()==="d")keys.right=false}function bindHold(b,d){const s=e=>{e.preventDefault();keys[d]=true},t=e=>{e.preventDefault();keys[d]=false};b.addEventListener("pointerdown",s);b.addEventListener("pointerup",t);b.addEventListener("pointercancel",t);b.addEventListener("pointerleave",t)}function clearMovement(){keys.left=false;keys.right=false}
function loop(now){const dt=Math.min(.034,(now-state.lastTime)/1000||0);state.lastTime=now;update(dt);draw();requestAnimationFrame(loop)}function update(dt){if(!state.started||state.complete)return;if(state.transactionDone&&state.cashAnim<1)state.cashAnim=Math.min(1,state.cashAnim+dt*.8);if(!paused()){let d=0;if(keys.left)d--;if(keys.right)d++;if(d){state.playerX+=d*235*dt;state.direction=d;state.walkTime+=dt*10;state.playerX=Math.max(70,Math.min(world.width-70,state.playerX))}}updateNearby();updateCamera(dt);if(state.transactionDone&&state.playerX>2430)completeMap()}function paused(){return!ui.dialogue.classList.contains("is-hidden")||!ui.panel.classList.contains("is-hidden")}function updateNearby(){if(paused()){state.nearby=null;ui.prompt.classList.add("is-hidden");return}const d=Math.abs(state.playerX-world.atmX);state.nearby=d<=120?"atm":null;if(state.nearby){ui.promptText.textContent=state.transactionDone?"ATM 영수증 확인":"수수료표와 ATM 확인";ui.prompt.classList.remove("is-hidden")}else ui.prompt.classList.add("is-hidden")}
function interact(){if(!state.started||paused()||state.nearby!=="atm")return;if(state.transactionDone){showDialogue([{speaker:"WH",avatar:"WH",text:"학원비 300,000원과 용돈 50,000원을 정확히 챙겼어. 수수료까지 포함한 계좌 차감액은 350,310원이었지."}]);return}if(!state.atmSeen){showDialogue([{speaker:"WH",avatar:"WH",text:"학원비 300,000원과 용돈 50,000원을 인출해야 해. 모두 얼마가 필요하지?"},{speaker:"ATM 안내",avatar:"ATM",text:"수수료는 거래 대금 구간별 수수료율과 추가 수수료를 합산하여 계좌에서 차감됩니다."},{speaker:"WH",avatar:"WH",text:"필요한 현금이 속한 구간을 찾고, 수수료까지 더한 계좌 필요액을 계산하면 되겠어."}],()=>{state.atmSeen=true;openAtm()})}else openAtm()}
function openAtm(){ui.problem.classList.toggle("is-hidden",state.planSolved);ui.success.classList.toggle("is-hidden",!state.planSolved);openPanel(ui.panel)}function submitPlan(e){e.preventDefault();const f=new FormData(ui.form),result=evaluateAtmPlan(f.get("rule"),f.get("cashNeeded"),f.get("interval"),f.get("percentageFee"),f.get("totalFee"),f.get("accountDebit"));ui.feedback.textContent=result.message;ui.feedback.className=`form-feedback ${result.ok?"is-success":"is-error"}`;if(!result.ok)return;state.planSolved=true;setTimeout(()=>{ui.problem.classList.add("is-hidden");ui.success.classList.remove("is-hidden");ui.confirm.focus()},500)}function showHint(){const hints=["학원비 300,000원과 용돈 50,000원을 먼저 더해 봐.","350,000원은 300,001원~400,000원 구간에 들어가므로 수수료율은 0.06%야.","비율 수수료는 350,000 × 0.06%이고, 여기에 추가 수수료 100원을 더해.","계좌 필요액은 인출할 현금과 총 수수료를 더한 금액이야."];ui.feedback.textContent=`힌트 · ${hints[Math.min(state.hintIndex,hints.length-1)]}`;ui.feedback.className="form-feedback";state.hintIndex++}
function completeTransaction(){closePanel(ui.panel);state.transactionDone=true;ui.wallet.textContent="인출 완료";ui.objective.textContent="학원비 봉투와 용돈을 챙겨 다음 숲길로 이동하자.";showDialogue([{speaker:"ATM",avatar:"ATM",text:"계좌에서 350,310원이 차감되었습니다. 현금 350,000원을 받으세요."},{speaker:"WH",avatar:"WH",text:"학원비 300,000원과 용돈 50,000원 준비 완료! 금액 구간에 맞는 수수료를 계산하니 필요한 계좌 잔액도 정확히 알 수 있었어."}])}
function useCalculator(event){const button=event.target.closest("[data-calc]");if(!button)return;const value=button.dataset.calc;if(value==="clear")return resetCalculator();if(value==="backspace"){calculatorTokens.pop();return renderCalculator()}if(value==="equals")return calculateResult();if(calculatorTokens.length===1&&calculatorTokens[0]==="오류")calculatorTokens=[];calculatorTokens.push(value);renderCalculator()}
function resetCalculator(){calculatorTokens=[];ui.calculatorDisplay.value="0"}
function renderCalculator(){const signs={"*":"×","/":"÷","-":"−"};ui.calculatorDisplay.value=calculatorTokens.length?calculatorTokens.map(token=>signs[token]??token).join(""):"0"}
function calculateResult(){if(!calculatorTokens.length)return;const expression=calculatorTokens.map(token=>token==="%"?"/100":token).join("");if(!/^[0-9+\-*/.]+$/.test(expression)){calculatorTokens=["오류"];return renderCalculator()}try{const result=Function(`"use strict";return (${expression})`)();if(!Number.isFinite(result))throw new Error("invalid");calculatorTokens=[String(Number(result.toFixed(6)))];renderCalculator()}catch{calculatorTokens=["오류"];renderCalculator()}}
function showDialogue(lines,cb=null){clearMovement();state.dialogueQueue=[...lines];state.dialogueCallback=cb;ui.dialogue.classList.remove("is-hidden");showLine()}function showLine(){const l=state.dialogueQueue[0];ui.speaker.textContent=l.speaker;ui.avatar.textContent=l.avatar;ui.avatar.style.background=l.avatar==="WH"?"#1b8f88":"#315f5b";ui.dialogueText.textContent=l.text;ui.dialogueNext.focus()}function advanceDialogue(){if(ui.dialogue.classList.contains("is-hidden"))return;state.dialogueQueue.shift();if(state.dialogueQueue.length)return showLine();ui.dialogue.classList.add("is-hidden");const cb=state.dialogueCallback;state.dialogueCallback=null;if(cb)cb();canvas.focus()}function openPanel(p){clearMovement();p.classList.remove("is-hidden");p.querySelector("input,button")?.focus()}function closePanel(p){p.classList.add("is-hidden");clearMovement();canvas.focus()}function completeMap(){state.complete=true;ui.hud.classList.add("is-hidden");ui.prompt.classList.add("is-hidden");ui.touch.classList.add("is-hidden");ui.complete.classList.remove("is-hidden");ui.replay.focus()}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);viewWidth=Math.max(320,r.width);viewHeight=Math.max(360,r.height);groundY=Math.max(330,viewHeight*.76);canvas.width=Math.round(viewWidth*d);canvas.height=Math.round(viewHeight*d);ctx.setTransform(d,0,0,d,0,0)}function updateCamera(dt){let t=state.playerX-viewWidth*.4;t=Math.max(0,Math.min(world.width-viewWidth,t));state.cameraX+=(t-state.cameraX)*(1-Math.exp(-4.5*dt))}function sx(x,p=1){return x-state.cameraX*p}function draw(){const d=Math.min(2,devicePixelRatio||1);ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,viewWidth,viewHeight);drawSky();drawGround();drawForest();drawShelter();drawAtm();drawMarkers();drawWH()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,groundY);g.addColorStop(0,"#a2d4bf");g.addColorStop(.7,"#e1deb2");g.addColorStop(1,"#d8bd7d");ctx.fillStyle=g;ctx.fillRect(0,0,viewWidth,viewHeight);ctx.fillStyle="#6d9b62";ctx.beginPath();ctx.moveTo(0,groundY-80);for(let x=-100;x<viewWidth+200;x+=190){const p=x-(state.cameraX*.15)%190;ctx.quadraticCurveTo(p+95,groundY-220,p+190,groundY-80)}ctx.lineTo(viewWidth,groundY);ctx.lineTo(0,groundY);ctx.fill()}function drawGround(){
  ctx.fillStyle="#86b86f";ctx.fillRect(0,groundY-118,viewWidth,118);
  ctx.fillStyle="#6f8f56";ctx.fillRect(0,groundY-28,viewWidth,36);
  const roadHeight=Math.max(170,viewHeight-groundY+82),tileWidth=900;
  const start=Math.floor(state.cameraX/tileWidth)*tileWidth;
  let drew=false;
  for(let wx=start;wx<state.cameraX+viewWidth+tileWidth;wx+=tileWidth){
    drew=assetManager.draw(ctx,"props.asphaltRoad",{x:sx(wx),y:viewHeight+8,width:tileWidth,height:roadHeight,anchorX:0,anchorY:1})||drew;
  }
  if(!drew){ctx.fillStyle="#77694d";ctx.fillRect(0,groundY+8,viewWidth,viewHeight-groundY);ctx.fillStyle="#bba775";ctx.fillRect(0,groundY-25,viewWidth,50)}
}
function drawForest(){for(const [x,h,a] of [[100,270,.95],[380,315,1],[700,285,.95],[1800,320,1],[2200,290,.95],[2550,310,1]])drawTree(x,h,a)}
function drawTree(x,height=300,alpha=1){const p=sx(x);if(p<-150||p>viewWidth+150)return;if(assetManager.draw(ctx,"props.tree",{x:p,y:groundY+4,height,alpha,anchorX:.5,anchorY:1}))return;ctx.fillStyle="#725039";ctx.fillRect(p-10,groundY-190,20,190);ctx.fillStyle="#4f8159";for(const [a,b,r] of [[0,-215,55],[-40,-185,39],[42,-185,43],[0,-255,37]]){ctx.beginPath();ctx.arc(p+a,groundY+b,r,0,Math.PI*2);ctx.fill()}}
function drawShelter(){
  const x=sx(1055);
  if(x<-420||x>viewWidth+420)return;
  if(assetManager.draw(ctx,"buildings.shuttleBusTransferCenter",{x,y:groundY+1,height:338,alpha:.98,anchorX:.5,anchorY:1})){
    drawShelterName(x,groundY-219);
    return;
  }
  ctx.fillStyle="#5c704f";ctx.fillRect(x-325,groundY-280,650,24);ctx.fillRect(x-310,groundY-256,15,256);ctx.fillRect(x+295,groundY-256,15,256);ctx.fillStyle="rgba(221,239,224,.38)";ctx.fillRect(x-295,groundY-250,590,220);drawShelterName(x,groundY-295)
}
function drawShelterName(x,y){
  ctx.save();ctx.textAlign="center";ctx.font="950 14px Pretendard, 'Noto Sans KR', system-ui";ctx.lineWidth=5;ctx.strokeStyle="rgba(255,255,255,.86)";ctx.fillStyle="#315f5b";
  const label="\uD478\uB978\uC194 \uD658\uC2B9 \uC27C\uD130";
  ctx.strokeText(label,x,y);ctx.fillText(label,x,y);ctx.restore();
}
function drawAtm(){
  const x=sx(world.atmX),y=groundY+4;
  ctx.fillStyle="rgba(24,35,48,.18)";ctx.beginPath();ctx.ellipse(x,y+4,62,14,0,0,Math.PI*2);ctx.fill();
  const drew=assetManager.draw(ctx,"props.atmMachine",{x,y,height:245,anchorX:.5,anchorY:1});
  if(!drew){const top=groundY-230;ctx.fillStyle="#dfe7df";roundRect(ctx,x-95,top,190,220,20);ctx.fill();ctx.fillStyle="#315f5b";ctx.fillRect(x-80,top+18,160,42);ctx.fillStyle="#fff";ctx.font="950 18px system-ui";ctx.textAlign="center";ctx.fillText("ATM",x,top+46);ctx.fillStyle="#173f40";roundRect(ctx,x-62,top+76,124,72,8);ctx.fill();ctx.fillStyle="#b9e0c6";ctx.font="900 12px system-ui";ctx.fillText(state.transactionDone?"DONE":"FEE TABLE",x,top+116);ctx.fillStyle="#e4b84d";ctx.beginPath();ctx.arc(x+55,top+177,10,0,Math.PI*2);ctx.fill()}
  if(state.cashAnim>0){ctx.fillStyle="#d9e6cf";for(let i=0;i<7;i++)ctx.fillRect(x-70+i*20,groundY-16-state.cashAnim*45,16,32)}
}
function drawMarkers(){if(!state.transactionDone)drawMarker(world.atmX,state.nearby==="atm")}function drawMarker(x,a){const p=sx(x),b=Math.sin(performance.now()/260)*4;ctx.fillStyle=a?"#e4b84d":"#7fb270";ctx.beginPath();ctx.arc(p,groundY-280+b,a?16:13,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 18px system-ui";ctx.textAlign="center";ctx.fillText(a?"E":"!",p,groundY-273+b)}function drawWH(){
  const p=sx(state.playerX),m=!paused()&&(keys.left||keys.right),s=m?Math.sin(state.walkTime)*11:0,b=m?Math.sin(state.walkTime*2)*2:0;
  if(assetManager.has("characters.wh")){
    ctx.fillStyle="rgba(24,35,48,.2)";ctx.beginPath();ctx.ellipse(p,groundY+5,36,10,0,0,Math.PI*2);ctx.fill();
    assetManager.draw(ctx,"characters.wh",{x:p,y:groundY+3+b,height:176,flipX:state.direction===-1,anchorX:.5,anchorY:1});
    return;
  }
  ctx.save();ctx.translate(p,groundY-2);ctx.scale(state.direction,1);ctx.strokeStyle="#1b2941";ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(-8,-48);ctx.lineTo(-12-s*.55,-5);ctx.moveTo(9,-48);ctx.lineTo(14+s*.55,-5);ctx.stroke();ctx.fillStyle="#1b8f88";roundRect(ctx,-27,-119,58,78,20);ctx.fill();ctx.fillStyle="#fff";ctx.font="950 12px system-ui";ctx.textAlign="center";ctx.fillText("WH",2,-76);ctx.fillStyle="#efc3a9";ctx.beginPath();ctx.arc(2,-151,35,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17223b";ctx.beginPath();ctx.arc(2,-162,36,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";for(const e of [2,21]){ctx.beginPath();ctx.ellipse(e,-151,8,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#126b68";ctx.beginPath();ctx.arc(e+2,-150,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff"}ctx.restore()}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
